### ISSUE TITLE
Modal overflow auto clips dropdown menu  

### ISSUE THREAD

**Issue by yusufnamdar** [TurkNet/design-system#334]
![image](https://user-images.githubusercontent.com/77000276/161557731-06851d60-9ea3-4608-bb84-fad0eafc1e37.png)

**Comment by yusufnamdar** [comment]
without auto
<img width="582" alt="Screenshot at Apr 04 16-34-50" src="https://user-images.githubusercontent.com/77000276/161560422-77117f5e-a988-464f-a29e-7ccdde85c256.png">

**Comment by ermanzohre** [comment]
@yusufnamdar this doesn't look like fixing our problem properly, because it's going down to the array's length and look like infinitive if the array length is high. But it helps to update ;)

**Comment by yusufnamdar** [comment]
I agree. as you said we could fix the case of clipped dropdowns that do not spill out of the screen like in the 2nd picture by making hardcoded overflow auto to dynamic. And, open another issue for that does have too many dropdown options and spilling all over the place
